=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WorkFlow_log.dtd
<!ELEMENT WorkFlow_log (source?,process+)>
  <!ELEMENT source EMPTY>
    <!ATTLIST source program (staffware|inconcert|pnet|IBM_MQ|other) #REQUIRED>
  <!ELEMENT process (case*)>
    <!ATTLIST process id ID #REQUIRED>
    <!ATTLIST process description CDATA "none">
    <!ELEMENT case (log_line*)>
      <!ATTLIST case id ID #REQUIRED>
      <!ATTLIST case description CDATA "none">
      <!ELEMENT log_line (task_name,task_instance?, event?, date?, time?)>
        <!ELEMENT task_name (#PCDATA)>
        <!ELEMENT task_instance (#PCDATA)>
        <!ELEMENT event EMPTY>
           <!ATTLIST event kind (normal|schedule|start|withdraw|suspend|resume|abort|complete) #REQUIRED>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>

=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WF-log examples/XML/Staffware/sw_ex_15.xml
<?xml version="1.0"?>
<!DOCTYPE WorkFlow_log SYSTEM "http://www.tm.tue.nl/it/research/workflow/mining/WorkFlow_log.dtd">
<WorkFlow_log><source program="staffware"/><process id="main_process"><case id="case_0"><log_line><task_name>Case start</task_name><event kind="normal"/><date>19-06-2002</date><time>12:58</time></log_line><log_line><task_name>Register</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:58</time></log_line><log_line><task_name>Register</task_name><event kind="complete"/><date>19-06-2002</date><time>12:58</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:58</time></log_line><log_line><task_name>Evaluate</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:58</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="complete"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="complete"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Evaluate</task_name><event kind="complete"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Archive</task_name><event kind="schedule"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Archive</task_name><event kind="complete"/><date>19-06-2002</date><time>13:00</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>19-06-2002</date><time>13:00</time></log_line></case><case id="case_1"><log_line><task_name>Case start</task_name><event kind="normal"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Register</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Register</task_name><event kind="complete"/><date>19-06-2002</date><time>12:35</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Evaluate</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="complete"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="complete"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Evaluate</task_name><event kind="complete"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="complete"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Check processing</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Check processing</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Check processing</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Check processing</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Archive</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Archive</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>19-06-2002</date><time>12:38</time></log_line></case><case id="case_2"><log_line><task_name>Case start</task_name><event kind="normal"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Register</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Register</task_name><event kind="complete"/><date>19-06-2002</date><time>12:35</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Evaluate</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Send questionaire</task_name><event kind="complete"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:36</time></log_line><log_line><task_name>Receive questionaire</task_name><event kind="withdraw"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Receive timeout</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Receive timeout</task_name><event kind="complete"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Evaluate</task_name><event kind="complete"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Proces complaint</task_name><event kind="complete"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Check processing</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:37</time></log_line><log_line><task_name>Check processing</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Archive</task_name><event kind="schedule"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Archive</task_name><event kind="complete"/><date>19-06-2002</date><time>12:38</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>19-06-2002</date><time>12:38</time></log_line></case></process></WorkFlow_log>
