=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WorkFlow_log.dtd
<!ELEMENT WorkFlow_log (source?,process+)>
  <!ELEMENT source EMPTY>
    <!ATTLIST source program (staffware|inconcert|pnet|IBM_MQ|other) #REQUIRED>
  <!ELEMENT process (case*)>
    <!ATTLIST process id ID #REQUIRED>
    <!ATTLIST process description CDATA "none">
    <!ELEMENT case (log_line*)>
      <!ATTLIST case id ID #REQUIRED>
      <!ATTLIST case description CDATA "none">
      <!ELEMENT log_line (task_name,task_instance?, event?, date?, time?)>
        <!ELEMENT task_name (#PCDATA)>
        <!ELEMENT task_instance (#PCDATA)>
        <!ELEMENT event EMPTY>
           <!ATTLIST event kind (normal|schedule|start|withdraw|suspend|resume|abort|complete) #REQUIRED>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>

=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WF-log examples/XML/Staffware/sw_ex_13.xml
<?xml version="1.0"?>
<!DOCTYPE WorkFlow_log SYSTEM "http://www.tm.tue.nl/it/research/workflow/mining/WorkFlow_log.dtd">
<WorkFlow_log><source program="staffware"/><process id="main_process"><case id="case_0"><log_line><task_name>Case start</task_name><event kind="normal"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKE</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKE</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>12-04-2002</date><time>15:17</time></log_line></case><case id="case_1"><log_line><task_name>Case start</task_name><event kind="normal"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKE</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKE</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>12-04-2002</date><time>15:17</time></log_line></case><case id="case_2"><log_line><task_name>Case start</task_name><event kind="normal"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKB</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKB</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKD</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKF</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKD</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKF</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>12-04-2002</date><time>15:17</time></log_line></case><case id="case_3"><log_line><task_name>Case start</task_name><event kind="normal"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKE</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKE</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>12-04-2002</date><time>15:18</time></log_line></case><case id="case_4"><log_line><task_name>Case start</task_name><event kind="normal"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>START</task_name><event kind="complete"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKB</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:16</time></log_line><log_line><task_name>TASKB</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKD</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKF</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKF</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKD</task_name><event kind="complete"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="schedule"/><date>12-04-2002</date><time>15:17</time></log_line><log_line><task_name>TASKG</task_name><event kind="complete"/><date>12-04-2002</date><time>15:18</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>12-04-2002</date><time>15:18</time></log_line></case></process></WorkFlow_log>

=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WF-log examples/XML/Staffware/sw_ex_06.xml
<?xml version="1.0"?>
<!DOCTYPE WorkFlow_log SYSTEM "http://www.tm.tue.nl/it/research/workflow/mining/WorkFlow_log.dtd">
<WorkFlow_log><source program="staffware"/><process id="main_process"><case id="case_0"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKI</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKI</task_name><event kind="complete"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:21</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>16-04-2002</date><time>15:22</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>16-04-2002</date><time>15:22</time></log_line><log_line><task_name>TASKJ</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:22</time></log_line><log_line><task_name>TASKJ</task_name><event kind="complete"/><date>16-04-2002</date><time>15:22</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>15:23</time></log_line></case><case id="case_1"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKI</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKI</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKJ</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKJ</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>15:27</time></log_line></case><case id="case_2"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKI</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:21</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>16-04-2002</date><time>15:21</time></log_line><log_line><task_name>TASKI</task_name><event kind="complete"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKJ</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKJ</task_name><event kind="complete"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>15:24</time></log_line></case><case id="case_3"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKI</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:20</time></log_line><log_line><task_name>TASKC</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:21</time></log_line><log_line><task_name>TASKC</task_name><event kind="complete"/><date>16-04-2002</date><time>15:21</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKI</task_name><event kind="complete"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKJ</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:23</time></log_line><log_line><task_name>TASKJ</task_name><event kind="complete"/><date>16-04-2002</date><time>15:24</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>15:24</time></log_line></case><case id="case_4"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKA</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKI</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKI</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKA</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKJ</task_name><event kind="schedule"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>TASKJ</task_name><event kind="complete"/><date>16-04-2002</date><time>15:27</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>15:27</time></log_line></case></process></WorkFlow_log>

=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WF-log examples/XML/Staffware/sw_ex_03.xml
<?xml version="1.0"?>
<!DOCTYPE WorkFlow_log SYSTEM "http://www.tm.tue.nl/it/research/workflow/mining/WorkFlow_log.dtd">
<WorkFlow_log><source program="staffware"/><process id="main_process"><case id="case_0"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="complete"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>task D</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>task D</task_name><event kind="complete"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>11:06</time></log_line></case><case id="case_1"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="withdraw"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task C</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task C</task_name><event kind="complete"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task D</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task D</task_name><event kind="complete"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>11:07</time></log_line></case><case id="case_2"><log_line><task_name>Case start</task_name><event kind="normal"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:06</time></log_line><log_line><task_name>taskB</task_name><event kind="withdraw"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task C</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task C</task_name><event kind="complete"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task D</task_name><event kind="schedule"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>task D</task_name><event kind="complete"/><date>16-04-2002</date><time>11:07</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>16-04-2002</date><time>11:07</time></log_line></case></process></WorkFlow_log>

=== victorcavero14/MIN/Practica1/Ejercicio/EMiT/EMiT/WF-log examples/XML/Staffware/sw_ex_14.xml
<?xml version="1.0"?>
<!DOCTYPE WorkFlow_log SYSTEM "http://www.tm.tue.nl/it/research/workflow/mining/WorkFlow_log.dtd">
<WorkFlow_log><source program="staffware"/><process id="main_process"><case id="case_0"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>B</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>B</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>D</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>D</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>G</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>G</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>09:06</time></log_line></case><case id="case_1"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>B</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>B</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>D</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>D</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>G</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>G</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>09:07</time></log_line></case><case id="case_2"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>C</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>C</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>F</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>F</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>H</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>H</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>09:07</time></log_line></case><case id="case_3"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>C</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>C</task_name><event kind="complete"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>F</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:05</time></log_line><log_line><task_name>F</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>H</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>H</task_name><event kind="complete"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>09:06</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>09:07</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>09:07</time></log_line></case><case id="case_4"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>13:47</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:47</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>13:49</time></log_line><log_line><task_name>C</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:49</time></log_line><log_line><task_name>C</task_name><event kind="complete"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>F</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>13:56</time></log_line><log_line><task_name>F</task_name><event kind="complete"/><date>18-04-2002</date><time>13:57</time></log_line><log_line><task_name>H</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:57</time></log_line><log_line><task_name>H</task_name><event kind="complete"/><date>18-04-2002</date><time>13:59</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:59</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>14:04</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>09:07</time></log_line></case><case id="case_5"><log_line><task_name>Case start</task_name><event kind="normal"/><date>18-04-2002</date><time>13:48</time></log_line><log_line><task_name>A</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:48</time></log_line><log_line><task_name>A</task_name><event kind="complete"/><date>18-04-2002</date><time>13:48</time></log_line><log_line><task_name>B</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:48</time></log_line><log_line><task_name>B</task_name><event kind="complete"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>D</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>E</task_name><event kind="schedule"/><date>18-04-2002</date><time>13:53</time></log_line><log_line><task_name>D</task_name><event kind="complete"/><date>18-04-2002</date><time>13:56</time></log_line><log_line><task_name>E</task_name><event kind="complete"/><date>18-04-2002</date><time>14:10</time></log_line><log_line><task_name>G</task_name><event kind="schedule"/><date>18-04-2002</date><time>14:10</time></log_line><log_line><task_name>G</task_name><event kind="complete"/><date>18-04-2002</date><time>14:13</time></log_line><log_line><task_name>I</task_name><event kind="schedule"/><date>18-04-2002</date><time>14:13</time></log_line><log_line><task_name>I</task_name><event kind="complete"/><date>18-04-2002</date><time>14:15</time></log_line><log_line><task_name>Case termination</task_name><event kind="normal"/><date>18-04-2002</date><time>14:15</time></log_line></case></process></WorkFlow_log>
